### ISSUE TITLE
undefined: swaggerfiles.Handler

### ISSUE THREAD

**Issue by gzsmhf** [swaggo/files#18]
I tried to use gin-swagger by exactly following the instructions from [here](https://github.com/swaggo/gin-swagger).
but got "undefined: swaggerfiles.Handler" error

**Comment by ubogdan** [comment]
What version of swagger/files are u using ?

**Comment by ZPascal** [comment]
@gzsmhf I think you're using v2, right? If you switch to v1.0.1 everything should work as expected.

**Comment by gzsmhf** [comment]
> @gzsmhf I think you're using v2, right? If you switch to v1.0.1 everything should work as expected.

Yes, 1.0.1 is working fine. Thank you.

**Comment by gzsmhf** [comment]
> What version of swagger/files are u using ?

v2.
I have switched to 1.0.1, all good now.

**Comment by ZPascal** [comment]
Great to hear that everything works now as expected.
