### ISSUE TITLE
b0xfile__swagger-ui-bundle.js.map.go is too big for Google App Engine (standard)

### ISSUE THREAD

**Issue by samprakos** [swaggo/files#2]
Max size allowed by App Engine - 32MB, this file is 44MB.  Is there a way to divide it into a couple of files?

**Comment by qushot** [comment]
@samprakos This probrem is resolved.
You can deploy to App Engine :-)
>[Removed 32MB file size limit for second generation runtimes.](https://cloud.google.com/sdk/docs/release-notes#app_engine_5)
